#!/usr/bin/env bash
#fizzbuzz fizz buzz
for i in {1..100}
do
    if [ $((i%5)) -eq "0" ] && [ $((i%3)) -eq "0" ]
    then
        echo "FizzBuzz"
        continue
    fi
    if [ $((i%5)) -eq "0" ]
    then
        echo "Buzz"
        continue
    fi
    if [ $((i%3)) -eq "0" ]
    then
        echo "Fizz"
        continue        
    fi
    echo "$i"
done
    
