#!/usr/bin/env bash
# Check if the /etc/passwd file exists and is readable
if [ -r "/etc/passwd" ]; then
  while IFS= read -r line; do
    echo "$line" > temp
    cut -d ":" -f 1,3,6  temp
  done < "/etc/passwd"
fi
