#!/usr/bin/env bash
#print best school 10 times with while loop if elif else
i="0"
while [ $i -lt 10 ]
do
    if [ "$i" == "3" ]
    then
        echo "bad luck"
    elif [ "$i" == "7" ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
